name: Documentation Improvement
description: Suggest improvements or report issues with documentation
title: 'docs(scope): brief description'
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation.

        **Note:** By submitting this issue, you agree to our [Contributor License Agreement (CLA)](../../CLA.md).

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Setup/Installation Guide
        - Architecture/Design Docs
        - Code Comments
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: 'e.g., README.md, docs/api/agents.md, lib/auth.ts (comments)'
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of improvement is needed?
      options:
        - Missing documentation
        - Outdated information
        - Unclear/confusing
        - Incorrect information
        - Typo/grammar
        - Missing examples
        - Missing links
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be improved or fixed?
      placeholder: Describe the documentation issue or improvement needed
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: What should the documentation say instead?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other helpful information, screenshots, or links
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this
          required: false
