name: Question or Help
description: Ask a question or request help with using BotHive
title: 'question: brief description'
labels: ['question', 'help wanted']
body:
  - type: markdown
    attributes:
      value: |
        ## Have a Question?

        Thank you for reaching out. Please search existing issues first to see if your question has been answered.

        **Note:** By submitting this issue, you agree to our [Contributor License Agreement (CLA)](../../CLA.md).

        ### Before asking:
        - Check the [README](../../README.md)
        - Review the [documentation](../../docs)
        - Search [existing issues](../../issues)

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Configuration
        - Usage/How-to
        - API/Integration
        - Database/Data
        - Authentication
        - Deployment
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?
      placeholder: Describe what you're working on and why you need this information
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What solutions have you already attempted?
      placeholder: |
        - Checked documentation
        - Tried X approach
        - Searched for Y
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your environment details
      placeholder: |
        - OS: [e.g., macOS 14.0]
        - Node version: [e.g., 20.10.0]
        - Package manager: [e.g., npm, yarn, pnpm]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other helpful information, screenshots, or code snippets
    validations:
      required: false
