name: Security Vulnerability Report
description: Report a security vulnerability (please report privately first!)
title: '[SECURITY] brief description'
labels: ['security']
body:
  - type: markdown
    attributes:
      value: |
        ## IMPORTANT - Security Vulnerabilities

        **If you have found a critical security vulnerability, please DO NOT create a public issue.**

        Instead, please report it privately through GitHub's Security Advisories:
        1. Go to the [Security tab](../../security/advisories)
        2. Click "Report a vulnerability"
        3. Fill out the private vulnerability report form

        This template is for **non-critical security improvements** or **already disclosed vulnerabilities**.

        **Note:** By submitting this issue, you agree to our [Contributor License Agreement (CLA)](../../CLA.md).

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Security best practice improvement)
        - Medium (Non-critical vulnerability)
        - High (Critical - please use private reporting!)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Data Validation/Sanitization
        - Dependency Vulnerability
        - Sensitive Data Exposure
        - Security Configuration
        - API Security
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Other
    validations:
      required: true

  - type: input
    id: affected_area
    attributes:
      label: Affected Component
      description: Which part of the codebase is affected?
      placeholder: 'e.g., /api/auth/signin, lib/database/operations.ts'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue or improvement
      placeholder: What is the security concern?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this vulnerability is exploited?
      placeholder: Describe the potential consequences
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can this issue be reproduced?
      placeholder: |
        1. Configure environment...
        2. Send request to...
        3. Observe behavior...
    validations:
      required: false

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Fix
      description: How should this be fixed?
      placeholder: Suggest a solution or mitigation
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant CVEs, articles, or documentation
      placeholder: |
        - CVE-XXXX-XXXXX
        - https://...
    validations:
      required: false

  - type: checkboxes
    id: verification
    attributes:
      label: Security Checklist
      options:
        - label: I have verified this is not a critical vulnerability requiring private disclosure
          required: true
        - label: I have checked if this affects the latest version
          required: true
