name: Remove Hacktoberfest Label

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (preview changes without applying)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Remove Hacktoberfest label from issues
        uses: actions/github-script@v7
        with:
          script: |
            const dryRun = '${{ github.event.inputs.dry_run }}' === 'true';

            console.log(`🎃 Remove Hacktoberfest Label Workflow`);
            console.log(`Dry run: ${dryRun ? 'YES' : 'NO'}`);
            console.log('');

            // Get all issues with hacktoberfest label
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'hacktoberfest',
              state: 'all',
              per_page: 100
            });

            console.log(`Found ${issues.length} issues with hacktoberfest label`);
            console.log('');

            let removed = 0;

            for (const issue of issues) {
              // Skip pull requests
              if (issue.pull_request) {
                continue;
              }

              if (dryRun) {
                console.log(`[DRY RUN] Would remove hacktoberfest label from #${issue.number}: ${issue.title}`);
              } else {
                try {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    name: 'hacktoberfest'
                  });
                  console.log(`✅ #${issue.number}: ${issue.title}`);
                  removed++;
                } catch (error) {
                  console.error(`❌ Failed to remove label from #${issue.number}: ${error.message}`);
                }
              }
            }

            // Summary
            console.log('');
            console.log('='.repeat(60));
            console.log('📊 Summary:');
            console.log(`   Removed: ${dryRun ? issues.length : removed}`);
            console.log(`   Total: ${issues.length}`);
            console.log('='.repeat(60));

            if (dryRun) {
              console.log('');
              console.log('💡 This was a dry run. Run with dry_run=false to apply changes.');
            }

            // Create step summary
            await core.summary
              .addHeading('Remove Hacktoberfest Label Results')
              .addRaw(dryRun ? '⚠️ **Dry Run Mode** - No changes were made' : '✅ **Labels Removed**')
              .addList([
                `Removed: ${dryRun ? issues.length : removed}`,
                `Total: ${issues.length}`
              ])
              .write();
